services:
  backend:
    build: ./backend
    container_name: chatbot-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app  
      - faiss_data:/app/data
      - ./backend/data/raw:/app/data/raw 
      - ./gcp-credentials.json:/app/gcp-credentials.json:ro
    environment:
      - ENV=development
      - GOOGLE_APPLICATION_CREDNTIALS =/app/gcp-credentials.json
  frontend:
    build: ./frontend
    container_name: chatbot-frontend
    ports:
      - "3000:5173"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000 
volumes:
  faiss_data: 
