import sys
from unittest.mock import MagicMock
import pytest


mlflow_mock = MagicMock()
sys.modules["mlflow"] = mlflow_mock

from app.main import app
from app.core.rag import rag_service

@pytest.fixture
def client():
    """
    Creates a TestClient where the RAG service is forced to be 'Ready'.
    """
    from fastapi.testclient import TestClient
    rag_service.is_ready = True
    rag_service.search = MagicMock(return_value=[
        {"text": "This is a mock document.", "metadata": {"source": "test.pdf", "page": 1}}
    ])
    rag_service.generate_answer = MagicMock(return_value={
        "answer": "This is a mock answer generated by pytest.",
        "sources": ["test.pdf (Page 1)"]
    })

    return TestClient(app)